Update tutorial to include Opencensus metrics #542
GoogleCloudPlatform/cloud-ops-sandbox pull request #702
Opened 2021-05-05 21:45 UTC by Ayelet41

2021-05-06 05:35 UTC, nicoleczhu commented on website/content/en/docs/User Guide/Learn Ops Management/cloud_monitoring.md
> +To search and view  metrics, type the name of the metric or the type of resource, for example to search [OpenCensus metrics](https://cloud-ops-sandbox.dev/docs/user-guide/#opencensus-to-become-opente
extra space: `view  metrics`

2021-05-06 05:36 UTC, nicoleczhu commented on website/content/en/docs/User Guide/Learn Ops Management/cloud_monitoring.md
> +This chart uses the  metric type `custom.googleapis.com/opencensus/grpc.io/client/completed_rpcs` (display name: "OpenCensus/grpc.io/client/completed_rpcs" ), and filters on the  `grpc_client_status`
What do you mean here: the `grpc_client_status` than is equal to "OK".

2021-05-06 05:39 UTC, nicoleczhu commented on website/content/en/docs/User Guide/Learn Ops Management/cloud_monitoring.md
> +As part of the `User Experience Dashboard` you can view a few of Opencensus metrics: `HTTP Request Count by Method`, `HTTP Response Errors` and `HTTP Request Latency, 99th Percentile` you edit the da
Some rephrase suggestions: 

The following example displays results where the `grpc_client_status` is not "OK" (e.g. PERMISSION_DENIED) and where the `grpc_client_method` does not include "google", i.e. errors from application services.

2021-05-06 05:40 UTC, nicoleczhu commented on website/content/en/docs/User Guide/Learn Ops Management/cloud_monitoring.md
> +As part of the `User Experience Dashboard` you can view a few of Opencensus metrics: `HTTP Request Count by Method`, `HTTP Response Errors` and `HTTP Request Latency, 99th Percentile` you edit the da
In addition to the default GCP [dashboards](https://cloud.google.com/monitoring/dashboards) mentioned above, Cloud Operations Sandbox provisions several...

2021-05-06 05:41 UTC, nicoleczhu commented on website/content/en/docs/User Guide/Learn Ops Management/cloud_monitoring.md
> +As part of the `User Experience Dashboard` you can view a few of Opencensus metrics: `HTTP Request Count by Method`, `HTTP Response Errors` and `HTTP Request Latency, 99th Percentile` you edit the da
In the `User Experience Dashboard`, you can also view Opencensus metrics like `HTTP Request Count by Method`, `HTTP Response Errors` and `HTTP Request Latency, 99th Percentile`. 

Additionally, you can edit the dashboard, add additional charts, and also open the chart in the Metrics explorer as shown below:

2021-05-06 05:42 UTC, nicoleczhu requested changes
See inline comments for requested changes. Thanks for this PR!

2021-05-06 10:38 UTC, Ayelet41 reviewed
Thanks @nicoleczhu for your helpful suggestions,  I updated all accordingly.

2021-05-07 07:36 UTC, nicoleczhu approved these changes

2021-05-07 07:37 UTC, nicoleczhu commented
@Ayelet41 I made some minor changes, and this is approved. Feel free to merge when you see fit

2021-05-07 08:21 UTC, merged