chore: pin terraform provider version
GoogleCloudPlatform/cloud-ops-sandbox pull request #960
Opened 2022-09-08 18:36 UTC by arbrown

fixes #865

2022-09-12 21:27 UTC, minherz requested changes
please, have a look at `required_providers` statement in the root terraform/ directory and align the constraints between the provide requirement declarations.

2022-09-12 21:27 UTC, minherz commented on terraform/monitoring/00_provider.tf
> +      version = "~> 3.23.0"
Please, align version constraint(s) in [terraform/01_provider.tf](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/62b12c8f74d7e9d6b242fe1a3d18f7f343fcb00f/terraform/01_provider.tf)  with the constraints you set in this file

2022-09-13 17:32 UTC, losalex approved these changes

2022-09-13 20:05 UTC, minherz approved these changes
lgtm. we will merge it once we confirm the fix for e2e test

2022-09-14 16:31 UTC, merged